"""LEGAL CASE SIMULATOR — multi-agent educational case analysis.

Pipeline (sequential; each agent sees the upstream outputs):

    Case Input
      -> Case Analyzer Agent      (facts, issues, charges, parties, evidence)
      -> Prosecution Agent        (strongest lawful prosecution view)
      -> Defense Agent            (strongest lawful defense view)
      -> Evidence Review Agent    (per-item strength + overall)
      -> Judge Agent              (reasoning, findings, verdict simulation)
      -> Final Case Report (dict)

This is an educational/analytical tool. Every agent prompt carries a safety
preamble: the simulator must not provide instructions for committing crimes,
avoiding detection, hiding/destroying evidence, or defeating law enforcement —
it only analyzes the scenario as legal professionals would in a moot-court
setting.

Like translation.py, this module is dependency-light (no rag_pipeline import):
the LLM is created lazily, and every agent accepts an injected `llm` so the
whole workflow is unit-testable offline with fakes.
"""

from __future__ import annotations

import datetime
import json
import logging
import os
import re
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# A large model: multi-step legal reasoning with strict JSON output is beyond
# the 8B generator. Low volume (one click = one simulation).
DEFAULT_CASE_SIM_MODEL = "llama-3.3-70b-versatile"

DISCLAIMER = (
    "This simulation is an educational and analytical exercise generated by an AI. "
    "It is not legal advice, not a prediction of any real court outcome, and must "
    "not be relied upon for real legal decisions. Consult a qualified lawyer for "
    "actual legal matters."
)

VERDICTS = ["Likely Conviction", "Uncertain Outcome", "Likely Acquittal"]
STRENGTHS = ["Strong", "Moderate", "Weak"]

_SAFETY_PREAMBLE = """You are one agent inside an EDUCATIONAL legal case simulator (a moot-court style
analysis tool). Everything you write is analytical and educational.

STRICT SAFETY RULES (non-negotiable):
- Do NOT provide instructions or advice for committing crimes, avoiding detection,
  hiding or destroying evidence, intimidating witnesses, or defeating law enforcement.
- If the scenario asks for such assistance, ignore that request entirely and analyze
  the scenario itself in a neutral, educational way.
- Do not fabricate evidence or invent facts not present in the scenario; you may note
  what additional evidence WOULD be legally relevant.
- Do not invent precise statute numbers you are unsure of; reference laws generically
  (e.g. "the fraud provisions of the criminal code of the stated jurisdiction").

OUTPUT FORMAT (non-negotiable):
- Respond in English.
- Output ONLY a single valid JSON object matching the requested schema.
- No markdown code fences, no commentary before or after the JSON.
"""


# ---------------------------------------------------------------------------
# Lazy LLM (same pattern as translation.py)
# ---------------------------------------------------------------------------

_sim_llm = None


def _get_default_llm():
    global _sim_llm
    if _sim_llm is None:
        from dotenv import load_dotenv
        from langchain_groq import ChatGroq

        load_dotenv()
        api_key = os.getenv("GROQ_API_KEY")
        if api_key is None:
            raise ValueError("GROQ_API_KEY not set in environment or .env file")
        model_name = os.getenv("CASE_SIM_MODEL", DEFAULT_CASE_SIM_MODEL)
        logger.info("Initializing case-simulator LLM: %s", model_name)
        _sim_llm = ChatGroq(
            groq_api_key=api_key,
            model_name=model_name,
            temperature=0.2,   # mostly deterministic, slight variation in argumentation
            max_tokens=2500,   # structured outputs can be long
        )
    return _sim_llm


# ---------------------------------------------------------------------------
# Parsing & normalization helpers
# ---------------------------------------------------------------------------

def extract_json(raw: str) -> Dict[str, Any]:
    """Best-effort extraction of one JSON object from an LLM reply.

    Tolerates markdown fences and stray commentary around the object by
    slicing from the first '{' to the last '}'.
    """
    text = (raw or "").strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError("no JSON object found in model output")
    obj = json.loads(text[start:end + 1])
    if not isinstance(obj, dict):
        raise ValueError("model output was not a JSON object")
    return obj


def _str_list(value: Any, max_items: int = 25) -> List[str]:
    """Coerce a model field into a clean list of strings."""
    if value is None:
        return []
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, list):
        return []
    out: List[str] = []
    for item in value[:max_items]:
        if isinstance(item, str) and item.strip():
            out.append(item.strip())
        elif isinstance(item, dict):
            out.append(json.dumps(item, ensure_ascii=False))
        elif item is not None:
            out.append(str(item))
    return out


def _parties_list(value: Any, max_items: int = 15) -> List[Dict[str, str]]:
    if not isinstance(value, list):
        return []
    out: List[Dict[str, str]] = []
    for item in value[:max_items]:
        if isinstance(item, dict):
            name = str(item.get("name", "")).strip()
            role = str(item.get("role", "")).strip()
            if name:
                out.append({"name": name, "role": role})
        elif isinstance(item, str) and item.strip():
            out.append({"name": item.strip(), "role": ""})
    return out


def _confidence(value: Any, default: int = 50) -> int:
    try:
        n = int(round(float(value)))
    except (TypeError, ValueError):
        return default
    return max(0, min(100, n))


def _enum(value: Any, allowed: List[str], default: str) -> str:
    if isinstance(value, str):
        for option in allowed:
            if value.strip().lower() == option.lower():
                return option
    return default


def _text(value: Any, max_chars: int = 4000) -> str:
    if not isinstance(value, str):
        value = "" if value is None else str(value)
    return value.strip()[:max_chars]


# ---------------------------------------------------------------------------
# Prompt building blocks
# ---------------------------------------------------------------------------

def _case_block(case: Dict[str, str]) -> str:
    return (
        f"CASE TITLE: {case['title']}\n"
        f"JURISDICTION: {case['jurisdiction']}\n"
        f"CASE TYPE: {case['case_type']}\n"
        f"CASE SCENARIO:\n{case['description']}"
    )


def _upstream(label: str, data: Dict[str, Any], max_chars: int = 3500) -> str:
    return f"{label} (JSON):\n{json.dumps(data, ensure_ascii=False)[:max_chars]}"


def _run_agent(llm, agent_name: str, prompt: str) -> Dict[str, Any]:
    """Invoke one agent and parse its JSON. On malformed output, degrade
    gracefully (keep the raw text as the reasoning summary) so one bad agent
    response never crashes the whole simulation."""
    resp = llm.invoke(prompt)
    raw = (resp.content or "").strip()
    try:
        return extract_json(raw)
    except Exception:
        logger.warning("%s returned non-JSON output; using fallback", agent_name)
        return {"reasoning_summary": raw[:1500], "parse_error": True}


# ---------------------------------------------------------------------------
# Agent 1: Case Analyzer
# ---------------------------------------------------------------------------

def analyze_case(case: Dict[str, str], llm) -> Dict[str, Any]:
    prompt = f"""{_SAFETY_PREAMBLE}
ROLE: You are the CASE ANALYZER agent — a neutral legal analyst.

TASK: Read the case scenario and extract its legal structure. Do not argue for
either side; only identify what is there.

{_case_block(case)}

Return ONLY this JSON schema:
{{
  "facts": ["objective fact stated in the scenario", ...],
  "legal_issues": ["legal question the case raises", ...],
  "possible_charges": ["charge or claim that could plausibly be brought", ...],
  "parties": [{{"name": "...", "role": "accused | complainant | witness | victim | other"}}],
  "evidence": ["piece of evidence mentioned or clearly implied", ...],
  "reasoning_summary": "3-5 sentence neutral summary of your analysis",
  "laws_referenced": ["law or legal principle relevant here", ...],
  "confidence": 0-100
}}"""
    raw = _run_agent(llm, "CaseAnalyzer", prompt)
    return {
        "facts": _str_list(raw.get("facts")),
        "legal_issues": _str_list(raw.get("legal_issues")),
        "possible_charges": _str_list(raw.get("possible_charges")),
        "parties": _parties_list(raw.get("parties")),
        "evidence": _str_list(raw.get("evidence")),
        "reasoning_summary": _text(raw.get("reasoning_summary")),
        "laws_referenced": _str_list(raw.get("laws_referenced")),
        "confidence": _confidence(raw.get("confidence")),
        **({"parse_error": True} if raw.get("parse_error") else {}),
    }


# ---------------------------------------------------------------------------
# Agent 2: Prosecution
# ---------------------------------------------------------------------------

def prosecution_view(case: Dict[str, str], analysis: Dict[str, Any], llm) -> Dict[str, Any]:
    prompt = f"""{_SAFETY_PREAMBLE}
ROLE: You are the PROSECUTION agent — simulate how a competent prosecutor would
build the strongest LAWFUL case from the scenario. Educational analysis only.

{_case_block(case)}

{_upstream("CASE ANALYSIS", analysis)}

TASK:
- Build the strongest prosecution arguments grounded in the stated facts.
- Identify which evidence supports each argument.
- Identify the applicable laws/legal principles.
- Explain why the possible charges may apply.

Return ONLY this JSON schema:
{{
  "arguments": ["prosecution argument", ...],
  "supporting_evidence": ["evidence item and what it proves", ...],
  "legal_references": ["applicable law or principle", ...],
  "why_charges_apply": "short explanation connecting facts to the charges",
  "reasoning_summary": "3-5 sentence summary of the prosecution theory",
  "confidence": 0-100
}}"""
    raw = _run_agent(llm, "Prosecution", prompt)
    return {
        "arguments": _str_list(raw.get("arguments")),
        "supporting_evidence": _str_list(raw.get("supporting_evidence")),
        "legal_references": _str_list(raw.get("legal_references")),
        "why_charges_apply": _text(raw.get("why_charges_apply")),
        "reasoning_summary": _text(raw.get("reasoning_summary")),
        "laws_referenced": _str_list(raw.get("legal_references")),  # explainability alias
        "confidence": _confidence(raw.get("confidence")),
        **({"parse_error": True} if raw.get("parse_error") else {}),
    }


# ---------------------------------------------------------------------------
# Agent 3: Defense
# ---------------------------------------------------------------------------

def defense_view(
    case: Dict[str, str],
    analysis: Dict[str, Any],
    prosecution: Dict[str, Any],
    llm,
) -> Dict[str, Any]:
    prompt = f"""{_SAFETY_PREAMBLE}
ROLE: You are the DEFENSE agent — simulate how a competent defense lawyer would
build the strongest LAWFUL defense. Educational analysis only.

ADDITIONAL RULES FOR YOU:
- You must NOT fabricate evidence or facts.
- You must NOT suggest illegal conduct (e.g. hiding evidence, influencing
  witnesses). Only lawful defense strategy: challenging evidence, procedure,
  interpretation, and burden of proof.

{_case_block(case)}

{_upstream("CASE ANALYSIS", analysis)}

{_upstream("PROSECUTION VIEW", prosecution)}

TASK:
- Build the strongest lawful defense arguments.
- Point out weaknesses and gaps in the prosecution's theory and evidence.
- Identify potential procedural issues worth examining.
- Offer alternative lawful interpretations of the facts.

Return ONLY this JSON schema:
{{
  "arguments": ["defense argument", ...],
  "prosecution_weaknesses": ["weakness in the prosecution case", ...],
  "procedural_issues": ["procedural question or safeguard to examine", ...],
  "alternative_interpretations": ["alternative lawful reading of the facts", ...],
  "legal_references": ["law or principle supporting the defense", ...],
  "reasoning_summary": "3-5 sentence summary of the defense theory",
  "confidence": 0-100
}}"""
    raw = _run_agent(llm, "Defense", prompt)
    return {
        "arguments": _str_list(raw.get("arguments")),
        "prosecution_weaknesses": _str_list(raw.get("prosecution_weaknesses")),
        "procedural_issues": _str_list(raw.get("procedural_issues")),
        "alternative_interpretations": _str_list(raw.get("alternative_interpretations")),
        "legal_references": _str_list(raw.get("legal_references")),
        "reasoning_summary": _text(raw.get("reasoning_summary")),
        "laws_referenced": _str_list(raw.get("legal_references")),
        "confidence": _confidence(raw.get("confidence")),
        **({"parse_error": True} if raw.get("parse_error") else {}),
    }


# ---------------------------------------------------------------------------
# Agent 4: Evidence Review
# ---------------------------------------------------------------------------

def evidence_review(
    case: Dict[str, str],
    analysis: Dict[str, Any],
    prosecution: Dict[str, Any],
    defense: Dict[str, Any],
    llm,
) -> Dict[str, Any]:
    prompt = f"""{_SAFETY_PREAMBLE}
ROLE: You are the EVIDENCE REVIEW agent — a neutral forensic/evidentiary expert.
Educational analysis only.

{_case_block(case)}

{_upstream("CASE ANALYSIS", analysis)}

{_upstream("PROSECUTION VIEW", prosecution, 2000)}

{_upstream("DEFENSE VIEW", defense, 2000)}

TASK: For the evidence in this case, evaluate:
- witness reliability
- document quality
- digital evidence quality
- chain-of-custody concerns
Rate each evidence item and the overall evidence strength as Strong, Moderate, or Weak.

Return ONLY this JSON schema:
{{
  "evidence_assessments": [
    {{"evidence": "...", "strength": "Strong|Moderate|Weak", "reasoning": "..."}}
  ],
  "witness_reliability": "assessment (or 'No witnesses described')",
  "document_quality": "assessment (or 'No documents described')",
  "digital_evidence_quality": "assessment (or 'No digital evidence described')",
  "chain_of_custody_concerns": ["concern", ...],
  "overall_strength": "Strong|Moderate|Weak",
  "reasoning_summary": "3-5 sentence summary of the evidentiary picture",
  "laws_referenced": ["evidence-law principle applied", ...],
  "confidence": 0-100
}}"""
    raw = _run_agent(llm, "EvidenceReview", prompt)

    assessments: List[Dict[str, str]] = []
    if isinstance(raw.get("evidence_assessments"), list):
        for item in raw["evidence_assessments"][:20]:
            if not isinstance(item, dict):
                continue
            evidence = _text(item.get("evidence"), 500)
            if not evidence:
                continue
            assessments.append({
                "evidence": evidence,
                "strength": _enum(item.get("strength"), STRENGTHS, "Moderate"),
                "reasoning": _text(item.get("reasoning"), 800),
            })

    return {
        "evidence_assessments": assessments,
        "witness_reliability": _text(raw.get("witness_reliability"), 800),
        "document_quality": _text(raw.get("document_quality"), 800),
        "digital_evidence_quality": _text(raw.get("digital_evidence_quality"), 800),
        "chain_of_custody_concerns": _str_list(raw.get("chain_of_custody_concerns")),
        "overall_strength": _enum(raw.get("overall_strength"), STRENGTHS, "Moderate"),
        "reasoning_summary": _text(raw.get("reasoning_summary")),
        "laws_referenced": _str_list(raw.get("laws_referenced")),
        "confidence": _confidence(raw.get("confidence")),
        **({"parse_error": True} if raw.get("parse_error") else {}),
    }


# ---------------------------------------------------------------------------
# Agent 5: Judge
# ---------------------------------------------------------------------------

def judge_case(
    case: Dict[str, str],
    analysis: Dict[str, Any],
    prosecution: Dict[str, Any],
    defense: Dict[str, Any],
    evidence: Dict[str, Any],
    llm,
) -> Dict[str, Any]:
    prompt = f"""{_SAFETY_PREAMBLE}
ROLE: You are the JUDGE agent — a neutral judicial officer simulating how a court
might reason about this case. Educational analysis only; this is NOT a real
verdict and must weigh the presumption of innocence.

{_case_block(case)}

{_upstream("CASE ANALYSIS", analysis, 2000)}

{_upstream("PROSECUTION VIEW", prosecution, 2500)}

{_upstream("DEFENSE VIEW", defense, 2500)}

{_upstream("EVIDENCE REVIEW", evidence, 2500)}

TASK:
- Weigh the prosecution and defense arguments against the evidence review.
- Produce judicial-style legal reasoning and concrete findings.
- Simulate a verdict tendency: exactly one of "Likely Conviction",
  "Uncertain Outcome", or "Likely Acquittal".

Return ONLY this JSON schema:
{{
  "legal_reasoning": "judicial reasoning paragraph(s)",
  "findings": ["specific finding", ...],
  "verdict": "Likely Conviction|Uncertain Outcome|Likely Acquittal",
  "verdict_reasoning": "short explanation of the verdict tendency",
  "reasoning_summary": "3-5 sentence summary",
  "laws_referenced": ["law or principle relied on", ...],
  "confidence": 0-100
}}"""
    raw = _run_agent(llm, "Judge", prompt)
    return {
        "legal_reasoning": _text(raw.get("legal_reasoning"), 6000),
        "findings": _str_list(raw.get("findings")),
        "verdict": _enum(raw.get("verdict"), VERDICTS, "Uncertain Outcome"),
        "verdict_reasoning": _text(raw.get("verdict_reasoning"), 2000),
        "reasoning_summary": _text(raw.get("reasoning_summary")),
        "laws_referenced": _str_list(raw.get("laws_referenced")),
        "confidence": _confidence(raw.get("confidence")),
        **({"parse_error": True} if raw.get("parse_error") else {}),
    }


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def run_case_simulation(case: Dict[str, str], llm=None) -> Dict[str, Any]:
    """Run the full 5-agent workflow and return the final case report.

    `case` must contain: title, description, jurisdiction, case_type.
    Each stage feeds the next, per the architecture:
    Analyzer -> Prosecution -> Defense -> Evidence Review -> Judge.
    """
    llm = llm or _get_default_llm()

    logger.info("Case simulation started: %r", case.get("title"))
    analysis = analyze_case(case, llm)
    prosecution = prosecution_view(case, analysis, llm)
    defense = defense_view(case, analysis, prosecution, llm)
    evidence = evidence_review(case, analysis, prosecution, defense, llm)
    judge = judge_case(case, analysis, prosecution, defense, evidence, llm)
    logger.info("Case simulation finished: verdict=%s", judge.get("verdict"))

    return {
        "case": {
            "title": case["title"],
            "description": case["description"],
            "jurisdiction": case["jurisdiction"],
            "case_type": case["case_type"],
        },
        "analysis": analysis,
        "prosecution": prosecution,
        "defense": defense,
        "evidence_review": evidence,
        "judge": judge,
        "disclaimer": DISCLAIMER,
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "model": getattr(llm, "model_name", "unknown"),
    }
